name: action2-yaml

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploying_to_azure:
    runs-on: windows-latest

    steps:
      - name: load-repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: install dependancy
        run: npm install

      - name: Azure Deployment
        uses: actions/function-action@v1
        with:
          app-name: "SADS"
          package: "."
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
